Resolves Issue #36
raptortech-js/ncf-web-contract-system pull request #40
Opened 2016-10-25 19:38 UTC by sawyerWeld

moves utility methods from main.js to a new utility.js

2016-10-26 14:49 UTC, raptortech-js commented
Build failing, ping me when it's ready for review.

2016-11-01 07:03 UTC, sawyerwelden15 commented
I've updated my changes, and it passes the checks this time. utilities.js was not staged for commits before.

2016-11-01 16:29 UTC, jackie-scholl requested changes

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/utility.js
> +  arraysEqual: arraysEqual,
Should this function really be exported? Why?

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/utility.js
> +  testResizeArray: testResizeArray,
Same here

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/utility.js
> +/* Wow. */
There should probably be a blank line above this

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/utility.js
> +  //return Math.floor(seconds) + ' seconds';
Does this commented out line need to stay in?

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/main.js
> +
Why was this line removed?

2016-11-01 16:29 UTC, raptortech-js commented on src/main/resources/js/main.js
> +
Why was this line added?

2016-11-01 20:19 UTC, raptortech-js commented
Resolves  #36

2016-11-02 15:43 UTC, raptortech-js commented on src/main/resources/js/main.js
> +);
I'd think files should probably end with a newline. See, for example, http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline. If you'd rather, I could accept this and we could fix it up as part of #48.

2016-11-02 15:43 UTC, raptortech-js commented on src/main/resources/js/utility.js
> +};
Same as above

2016-11-02 15:44 UTC, raptortech-js commented
Thanks for fixing all of the previously mentioned issues, if you could just add line breaks to the end of those two files that'd be great, thanks.

2016-11-07 18:14 UTC, sawyerWeld commented on src/main/resources/js/utility.js
> +};
all files have a new line at the end

2016-11-08 19:44 UTC, jackie-scholl approved these changes

2016-11-08 19:45 UTC, merged